
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./practice:/www/
      - ./unit.json:/docker-entrypoint.d/config.json:ro
    networks:
        - app-network
  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
